export const DRIVER_PHONE_DUPLICATE_WARNING = 'DRIVER_PHONE_DUPLICATE_WARNING';
export const DRIVER_INVITED = 'DRIVER_INVITED';
export const DRIVER_INVITATION_ACCEPTED = 'DRIVER_INVITATION_ACCEPTED';
export const DRIVER_INVITATION_TOKEN_TTL_HOURS = 72;
