/**
 * Actions d'audit enregistrées dans la table `audit_logs`.
 *
 * Chaque action est préfixée par le nom de la ressource
 * pour faciliter le filtrage et la recherche.
 */
export enum AuditAction {
  // Auth
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_REFRESH = 'AUTH_REFRESH',
  AUTH_PASSWORD_CHANGED = 'AUTH_PASSWORD_CHANGED',
  AUTH_TOKEN_REUSE_DETECTED = 'AUTH_TOKEN_REUSE_DETECTED',

  // Groupements
  GROUPEMENT_CREATED = 'GROUPEMENT_CREATED',
  GROUPEMENT_UPDATED = 'GROUPEMENT_UPDATED',
  GROUPEMENT_DELETED = 'GROUPEMENT_DELETED',

  // Users
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_INVITED = 'USER_INVITED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',

  // Drivers
  DRIVER_CREATED = 'DRIVER_CREATED',
  DRIVER_UPDATED = 'DRIVER_UPDATED',
  DRIVER_DELETED = 'DRIVER_DELETED',
  DRIVER_STATUS_CHANGED = 'DRIVER_STATUS_CHANGED',
  DRIVER_PHONE_DUPLICATE_WARNING = 'DRIVER_PHONE_DUPLICATE_WARNING',

  // Clients
  CLIENT_CREATED = 'CLIENT_CREATED',
  CLIENT_UPDATED = 'CLIENT_UPDATED',
  CLIENT_DELETED = 'CLIENT_DELETED',
  CLIENT_ARCHIVED = 'CLIENT_ARCHIVED',
  CLIENT_UNARCHIVED = 'CLIENT_UNARCHIVED',
  CLIENT_BLACKLISTED = 'CLIENT_BLACKLISTED',
  CLIENT_UNBLACKLISTED = 'CLIENT_UNBLACKLISTED',
  CLIENT_ADDRESS_CREATED = 'CLIENT_ADDRESS_CREATED',
  CLIENT_ADDRESS_UPDATED = 'CLIENT_ADDRESS_UPDATED',
  CLIENT_ADDRESS_DELETED = 'CLIENT_ADDRESS_DELETED',

  // Courses
  COURSE_CREATED = 'COURSE_CREATED',
  COURSE_UPDATED = 'COURSE_UPDATED',
  COURSE_STATUS_CHANGED = 'COURSE_STATUS_CHANGED',
  COURSE_DELETED = 'COURSE_DELETED',
}
